spring.application.name=bishop-prototype
weyland.audit.mode=KAFKA
spring.kafka.bootstrap-servers=kafka:9092
weyland.command.queue.max-size=100
weyland.audit.kafka.topic=weyland-audit
management.endpoints.web.exposure.include=*
management.endpoint.prometheus.enabled=true
